### ISSUE TITLE
Building from source on ubuntu 20

### ISSUE THREAD

**Issue by realsetvin** [MattF42/PePe-core#2]
After building from source I attempt to run the QT file and encounter this issue

The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 22 (Invalid argument) on X server ":0"
      after 403 requests (403 known processed) with 0 events remaining.
when I attempt to run the QT

Found another issue referencing this 
https://github.com/bitcoin/bitcoin/issues/18537

**Comment by MattF42** [comment]
Should be fixed by [https://github.com/MattF42/PePe-core/commit/c27512e335d6c846f5dbcc8d67ced7fa679ef79f](https://github.com/MattF42/PePe-core/commit/c27512e335d6c846f5dbcc8d67ced7fa679ef79f)
