### ISSUE TITLE
Solo mined coins not shown anywhere

### ISSUE THREAD

**Issue by aliensex** [MattF42/PePe-core#23]
Today about 3:22 (0 gmt) +-1m solo block was mined, core wallet showed a notification with right label and 5000 coins, also a ccminer had a green Yes!
But in a wallet no sign of new coins, no new transaction, balance unchanged, getbalance show same, 
2. Address used for solo has no records on explorer.
3. Orphans blocks from explorer happened at different time.
4. Wallet launched with -rescan, but seems do not even work.

**Comment by MattF42** [comment]
Hi,

Solo mining directly to a node with CCminer is known to work - that's how we fed the network hash in the run up to the hardfork.    Do you have a blockheight you think this happened at ?  Likely got orphaned. The eliqidus based explorers have a few issues, but I would hope https://pepew.ccore.online/ would record it correctly.  If you can provide the wallet address you are solo mining against that would help as well.

**Comment by aliensex** [comment]
Only time.
P9kTL23P5RLnS4Fx2pNLgB2u4Siw324cSW

**Comment by MattF42** [comment]
My guess is that the block orphaned.   If it happens again, please let me know the precise blockheight.  #CNR
